### ISSUE TITLE
[Bug]: Messenger not showing notifications

### ISSUE THREAD

**Issue by Lefky** [ferdium/ferdium-recipes#246] opened 2022-11-24 09:37 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.0

### Recipe Name

Facebook Messenger

### Recipe Version

1.7.5

### Steps to reproduce

1. Add messenger service
2. Get a new message
3. Notice no notification counter is shown 

### Expected Behavior

Like with other services a notification badge is shown

### Actual Behavior

No notification badge is present

### Screenshots

![image](https://user-images.githubusercontent.com/10397178/203749417-d153a403-df3a-4df6-ae04-fe6d21703300.png)

### Additional Information

I know rambox does this as expected. Inspiration can be found there.

**Comment by SpecialAro** [comment] 2022-11-24 13:04
I can confirm this to be working with 1.7.6 version of the recipe which is on Ferdium 6.2.1-nihgtly.50

This issue will find its natural resolution once we release a new version to the stable channel.

![image](https://user-images.githubusercontent.com/37463445/203791274-ad76f4ae-2916-4d82-9661-071f73462b12.png)

**Comment by nathanaelhoun** [comment] 2023-02-15 20:44
Ferdium 6.2.2 has been released, this issue should be fixed now. Please reopen it if the problem is still present.

**Closed by nathanaelhoun** 2023-02-15 20:44 UTC
Labels: bug :beetle:, recipe :bookmark_tabs:
