### ISSUE TITLE
[Bug]: Discord app does not show the search box when used within ferdi

### ISSUE THREAD

**Issue by kishaningithub** [ferdium/ferdium-recipes#31] opened 2022-05-18 03:29 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nightly.39

### Recipe Name

discord

### Recipe Version

Latest (1.7.2)

### Steps to reproduce

1. Open ferdium discord channel within ferdi.

### Expected Behavior

The search box should be visible

### Actual Behavior

The search box is not visible

### Screenshots

# When Opened in Ferdi
<img width="1648" alt="Screenshot 2022-05-18 at 8 58 47 AM" src="https://user-images.githubusercontent.com/763760/168951321-b6b5cfd9-69d7-4d70-9bde-f7a13dd53cdb.png">

# When Opened in firefox
<img width="1655" alt="Screenshot 2022-05-18 at 8 58 03 AM" src="https://user-images.githubusercontent.com/763760/168951255-6341f5b4-3390-44e3-9338-112568053e28.png">

**Comment by kishaningithub** [comment] 2022-05-18 03:34
## Work around

When i changed useragent in the ferdi settings to "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0" was able to see the search box (screenshot below)

<img width="666" alt="Screenshot 2022-05-18 at 9 03 52 AM" src="https://user-images.githubusercontent.com/763760/168951847-17c4b5a5-87f9-436f-ba32-8983c0c66a1f.png">

**Comment by kishaningithub** [comment] 2022-05-25 04:46
The catch with the workaround i see is that it is for some reason asking me to login every time i reopen ferdium/reload the service.

**Comment by JowJoris** [comment] 2022-05-27 20:40
@kishaningithub I am using the latest version of Ferdium (beta 1) and recipe version 1.7.3 of Discord.
I can't reproduce the issue.
Is it still present for you after updated Ferdium and the Discord service?

**Comment by kishaningithub** [comment] 2022-05-30 04:52
@JowJoris It is the same..  (screenshot below)

<img width="732" alt="Screenshot 2022-05-30 at 10 21 45 AM" src="https://user-images.githubusercontent.com/763760/170919354-fb100a36-7d23-4b37-9cd0-c04f8d817e7f.png">

**Comment by mydarkstar** [comment] 2022-06-03 19:20
Hi @kishaningithub. Thanks for finding a workaround for this!

The issue seems to stem from the following line:
https://github.com/ferdium/ferdium-recipes/blob/main/recipes/discord/index.js#L6

Ferdium tries to act as the official Discord client here. But it may indeed be better to act as a Chromium browser (Firefox isn't needed and could lead to confusions).

You can overwrite the User Agent by returning a different string. This would fix it for all users!

**Comment by vraravam** [comment] 2022-06-16 01:14
@kishaningithub - maybe you can comment out https://github.com/ferdium/ferdium-recipes/blob/main/recipes/discord/index.js#L2-L7 and check with also reverting the user-agent back ? If that works, please raise a PR for the fix?

**Comment by mydarkstar** [comment] 2022-06-27 17:44
Is there any update on this case? Is there something we need to change in the code base? Can we close this issue?

**Comment by kishaningithub** [comment] 2022-06-27 18:55
The issue still persists for me, tried changing the user agent but for some reason the discord app constantly requires a re login during service reload or ferdium restart. This is something I am debugging. Sorry for the delays.

**Comment by kishaningithub** [comment] 2022-07-03 13:14
For some weird reason while using the chrome's user agent explicitly the problem disappears and continuous re login does not happen.. Tested this multiple times today in my Mac with M1 Chip since it worked flawlessly have raised a PR (linked to this issue)

**Closed** 2022-07-03 23:41 UTC
Labels: question
